import {chromium} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const email=`e2e-${Date.now()}@example.com`,password='Teste-navegador-123';
try{
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('button',{name:'Criar conta gratuita'}).click();
 await page.getByLabel('Seu nome',{exact:true}).fill('Visitante');
 await page.getByLabel('E-mail',{exact:true}).fill(email);
 await page.getByLabel('Senha',{exact:true}).fill(password);
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Criar conta',exact:true}).click();
 await page.getByRole('heading',{name:'Informação que faz bem.'}).waitFor();
 await page.getByRole('button',{name:'Experimente sinvastatina + toranja'}).click();
 await page.getByRole('button',{name:'Verificar interação',exact:true}).click();
 await page.getByRole('heading',{name:'Interação encontrada · risco ainda não classificado'}).waitFor();
 await page.getByRole('button',{name:'Grafo de conhecimento',exact:true}).click();
 await page.getByRole('button',{name:'Medicamento',exact:true}).click();
 await page.getByRole('button',{name:'Fechar resultado'}).click();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'../preview-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Meu perfil clínico',exact:true}).click();
 await page.getByLabel('Idade (anos)').fill('67');
 await page.getByLabel('Peso (kg)').fill('80');
 await page.getByLabel('Altura (cm)').fill('180');
 await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Perfil salvo'}).waitFor();
 await page.getByRole('button',{name:'Histórico',exact:true}).click();
 await page.getByRole('button',{name:'Reabrir'}).first().click();
 await page.getByRole('heading',{name:'Interação encontrada · risco ainda não classificado'}).waitFor();
 await page.getByRole('button',{name:'Dados e privacidade',exact:true}).click();
 await page.getByRole('button',{name:'Visualizar meus dados'}).click();
 await page.getByRole('heading',{name:'Consentimento versão 1.0'}).waitFor();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Exportar JSON'}).click();
 const download=await downloadPromise;
 if(download.suggestedFilename()!=='meus-dados-drug-food-checker.json')throw new Error('Exportação inválida');
 await page.getByRole('button',{name:'Consultar interação',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=1);
 await page.getByRole('button',{name:'Fechar aviso'}).click().catch(()=>{});
 await page.screenshot({path:'../preview-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Overflow em celular');
 await page.setViewportSize({width:1440,height:1080});
 await page.getByRole('button',{name:'Dados e privacidade',exact:true}).click();
 await page.getByRole('button',{name:'Solicitar exclusão'}).click();
 await page.getByLabel('Confirme sua senha').fill(password);
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Excluir definitivamente'}).click();
 await page.getByRole('heading',{name:'Que bom ter você aqui.'}).waitFor();
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('PASS: cadastro, consentimento, consulta, grafo, perfil, histórico, exportação, responsividade e exclusão; sem erros JavaScript.');
} finally {await browser.close()}
